@startuml
!include <C4/C4_Container>

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons2

!include DEVICONS/mongodb.puml
!include DEVICONS/redis.puml
!include DEVICONS/fastapi.puml


Person(client, "Consumidor", "Exemplo: Aplicativo web ou mobile, Prowlarr, etc")

System_Ext(flaresolverr, "FlareSolverr", "Proxy que resolve desafios do Cloudflare para automatizar acessos durante a raspagem.")

Boundary(externalApis, "APIS Externas") {
  System_Ext(imdbSuggestionApi, "IMDb Suggestion API")
  System_Ext(tmdbTrendingApi, "TMDB Trending API")
}

System_Boundary(betor, "Betor") {
  Container(betorApi, "RestFul API", "Python e FastAPI", "Dispara raspagens, lista items e acompanha status de tarefas.", $sprite="fastapi")
  Container(betorScrapyd, "Betor ScrapyD", "ScrapyD", "Serviço que permite executar, agendar e gerenciar spiders Scrapy remotamente via API.")

  Boundary(storageLayer, "Armazenamento / Cache") {
    SystemDb(mongoDb, "MongoDB", "Armazenamento de raw items e items", $sprite="mongodb")
    SystemDb(redisCache, "Redis Cache", $sprite="redis")
    SystemDb(redisLock, "Redis Lock", $sprite="redis")
    SystemDb(redisQueue, "Redis Queue", $sprite="redis")
  }

  Boundary(processingLayer, "Processamento Assíncrono") {
    Container(betorWorkerItems, "Betor Worker Items", "Celery Worker", "Processa raw item em items e enriquece items.")
    Container(betorWorkerTorrents, "Betor Worker Torrents", "Celery Worker", "Consulta metadados de torrents para enriquecer items.")
    SystemQueue(betorQueueItems, "Betor Items Queue", "Fila de tarefas para enriquecimento de items", $sprite="redis")
    SystemQueue(betorQueueTorrents, "Betor Torrent Queue", "Fila de tarefas que envolvem interação com torrent", $sprite="redis")
  }

  Rel(betorApi, mongoDb, "Consulta items", "TCP")
  Rel(betorApi, redisCache, "Cache para busca textual", "TCP")
  Rel(betorApi, betorScrapyd, "Dispara e acompanha raspagens", "HTTP")
  Rel(betorApi, betorQueueItems, "Acompanha resultados e status", "Celery API")
  Rel(betorScrapyd, flaresolverr, "Resolve desafios", "HTTP")
  Rel(betorScrapyd, mongoDb, "Armazena raw items", "TCP")
  Rel(betorScrapyd, redisCache, "Realiza cache de páginas", "TCP")
  Rel(betorScrapyd, redisLock, "Lock para gerenciar uso de sessões FlareSolverr", "TCP")
  Rel(betorScrapyd, betorQueueItems, "Enfilera tarefa para processar raw item", "Assíncrono Celery")
  Rel(betorWorkerItems, mongoDb, "Armazena e atualiza items", "TCP")
  Rel(betorWorkerItems, imdbSuggestionApi, "Consulta IMDb ID", "HTTP")
  Rel(betorWorkerItems, tmdbTrendingApi, "Consulta TMDB ID", "HTTP")
  Rel(betorWorkerItems, betorQueueItems, "Consome tarefas", "Celery")
  Rel(betorWorkerTorrents, mongoDb, "Atualiza items", "TCP")
  Rel(betorWorkerTorrents, betorQueueTorrents, "Consome tarefas", "Celery")
  Rel(betorQueueItems, redisQueue, "Backend e Broker", "TCP")
  Rel(betorQueueTorrents, redisQueue, "Backend e Broker", "TCP")
}

Rel(client, betorApi, "Consome", "HTTP - RESTful API")
@enduml
